#!/bin/sh
# User-specific environment and PATHs, sourced by bash and other shells.
# See notes in ~/.bash_profile.

# default for local users; allows non-root to do `virsh list` and see all vms
export LIBVIRT_DEFAULT_URI="qemu:///system"

# blast that caps lock away in Wayland too
export XKB_DEFAULT_OPTIONS=ctrl:nocaps
export MOZ_ENABLE_WAYLAND=1

# if not root
if [ "$(id -u)" -ne 0 ]; then
	ADW_DISABLE_PORTAL=1
	export ADW_DISABLE_PORTAL
	# nodejs - global packages per user, avoids need for sudo in: npm i -g <pkgname>
	# https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally
	# export NPM_CONFIG_PREFIX=~/.npm-global

	mkdir -p $HOME/go/bin
	# mkdir -p $HOME/go/bin $HOME/.cargo/bin
	# PATH="$PATH:$HOME/go/bin:$NPM_CONFIG_PREFIX/bin:$HOME/.local/bin:$HOME/.cargo/bin"
	PATH="$PATH:$HOME/go/bin:$HOME/.local/bin"
	export PATH

	# source any private keys and such
	if [ -f "$HOME/.env" ]; then
		. $HOME/.env
	fi
fi
