#!/bin/sh
# Xorg session configuration for dwm
# Display managers (most Xorg-aware anyway) source script.
# startx via .xinitrc sources this script.

. /etc/os-release # for ID
HOSTNAME=$(uname -n)
export XDG_CURRENT_DESKTOP="X-Generic"

# establish a DBUS session if not already running
[ -z "$DBUS_SESSION_BUS_ADDRESS" ] && eval $(/usr/bin/dbus-launch --exit-with-session --sh-syntax)
dbus-update-activation-environment --verbose --all

# init keyring
eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)
# export keyring globals
export GNOME_KEYRING_CONTROL GNOME_KEYRING_PID GPG_AGENT_INFO SSH_AUTH_SOCK

# OS specific
case "$ID" in
void)
	# void isn't a systemd distribution
	pipewire &
	;;
opensuse-tumbleweed) ;;
debian) ;;
esac

# Host specific
# xrdb -merge ~/.config/xinit/.Xresources-${HOSTNAME}
case "$HOSTNAME" in
elron)
	# desktop workstation
	xrandr --output DisplayPort-0 --mode 2560x1440 --left-of HDMI-A-0
	xrandr --output HDMI-A-0 --primary --mode 2560x1440 --rate 143.91
	# redshift &
	# sudo ddcutil -d 2 setvcp 60 0x0f
	xset +dpms               # enable display power management system
	xset dpms 1200 2400 3600 # standby, suspend, off; xset q to see values
	xset s blank             # blank screen on time out
	xset s 2000 3000         # blank tied to slock
	;;
hoppy)
	# laptop
	# allow alacritty to scale same on elron (2 hidpi monitors) and laptop (1980x1080)
	export WINIT_X11_SCALE_FACTOR="1.15"
	xinput set-prop "DELL0A36:00 0488:101A Touchpad" "libinput Tapping Enabled" 1
	xinput set-prop "DELL0A36:00 0488:101A Touchpad" "libinput Natural Scrolling Enabled" 1
	xinput set-prop "DELL0A36:00 0488:101A Touchpad" "libinput Disable While Typing Enabled" 1
	xinput set-prop "DELL0A36:00 0488:101A Touchpad" "libinput Accel Speed" 0.5
	# save a bit of power
	rfkill block bluetooth
	# bit more aggressive on shutting display off on the laptop
	xset +dpms             # enable display power management system
	xset dpms 300 600 1200 # standby, suspend, off; xset q to see values
	xset s blank           # blank screen on time out
	xset s 180 120         # blank tied to slock
	;;
esac

xss-lock slock &                                         # set slock as the lock handler
picom -b --backend glx --vsync                           # picom provides more than eye candy
feh --no-fehbg --bg-center ~/.config/wallpaper/defaultbg # background, a symlink
dunst &                                                  # notification daemon for X
tikiblocks -o xsetroot &                                 # status bar updates
/usr/libexec/xfce-polkit &                               # polkit agent for gui when app needs to acquire permission
# the window manager is started by startx/.xinitrc or a display manager
