#!/bin/sh
# Session configuration for wl-roots compositors like dwl
# This script follows the general approac in ~/.xprofile for XOrg
# Scripts calling this:
# ~/.local/bin/startdwl

. /etc/os-release # for ID
HOSTNAME=$(uname -n)
export XDG_CURRENT_DESKTOP="X-Generic"

# init keyring

# OS specific
case "$ID" in
void) ;;
eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh);
export GNOME_KEYRING_CONTROL GNOME_KEYRING_PID GPG_AGENT_INFO SSH_AUTH_SOCK;
pipewire &;
mako &;
/usr/libexec/xfce-polkit &;;
opensuse-tumbleweed) ;;
debian) ;;
esac

# Host specific
case "$HOSTNAME" in
elron) ;;
hoppy)
	# laptop
	# allow alacritty to scale same on elron (2 hidpi monitors) and laptop (1980x1080)
	export WINIT_X11_SCALE_FACTOR="1.25"
	# save a bit of power
	rfkill block bluetooth
	;;
esac

export XKB_DEFAULT_OPTIONS=ctrl:nocaps # nocaps for the win
