#!/bin/sh
# Xorg startup script for dwm
# for ID
. /etc/os-release
HOSTNAME=$(uname -n)
export XDG_CURRENT_DESKTOP="X-Generic"

# While I mostly run Void Linux as a daily driver...
case "$ID" in
void)
	# not started as a service on Void
	pipewire &
	;;
opensuse-tumbleweed) ;;
arch) ;;
esac

# xrdb -merge ~/.config/xinit/.Xresources-${HOSTNAME}

case "$HOSTNAME" in
elron)
	picom -b --backend glx --vsync # more than just eye candy
	# colour temp of screen
	# redshift &
	# sudo ddcutil -d 2 setvcp 60 0x0f
	# xrandr --output HDMI-A-1 --primary --output DisplayPort-2 --right-of HDMI-A-1
	;;
lapin) ;;
pika) ;;
hoppy)
	export WINIT_X11_SCALE_FACTOR="1" # allow alacritty to scale same on elron (hidpi) and laptop (1980)
	picom -b                          # laptop doesn't like --sync; more than just eye candy
	;;
esac

# init keyring
eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)
# export keyring globals
export GNOME_KEYRING_CONTROL GNOME_KEYRING_PID GPG_AGENT_INFO SSH_AUTH_SOCK

setxkbmap -option ctrl:nocaps # CAPSLOCK should never exist, make it a ctrl key
xset +dpms                    # enable display power management system
xset dpms 300 600 1200        # standby, suspend, off; xset q to see values
xset s blank                  # blank screen on time out
xset s 180 120                # blank tied to slock
xss-lock slock &              # set slock as the lock handler

# Status bar for dwm, see https://github.com/solutionroute/suckless-patches
# slstatus &

feh --no-fehbg --bg-center ~/.config/wallpaper/defaultbg # background
dunst &                                                  # dbus-aware notification daemon
dbus-run-session dwm                                     # start dwm in dbus session context
