#!/bin/sh
# Xorg session configuration
# ~/.xinitrc sources this

. /etc/os-release # for ID
HOSTNAME=$(uname -n)

# Host specific
case "$HOSTNAME" in
elron)
	# desktop workstation
	xrandr --output DisplayPort-0 --mode 2560x1440 --left-of HDMI-A-0
	xrandr --output HDMI-A-0 --primary --mode 2560x1440 --rate 143.91
	# redshift &
	# sudo ddcutil -d 2 setvcp 60 0x0f
	xset +dpms               # enable display power management system
	xset dpms 1200 2400 3600 # standby, suspend, off; xset q to see values
	xset s blank             # blank screen on time out
	xset s 2000 3000         # blank tied to slock
	;;
hoppy)
	# laptop
	# force alacritty to scale same on elron (2 hidpi monitors) and laptop (1980x1080)
	export WINIT_X11_SCALE_FACTOR="1.15"
	xinput set-prop "DELL0A36:00 0488:101A Touchpad" "libinput Tapping Enabled" 1
	xinput set-prop "DELL0A36:00 0488:101A Touchpad" "libinput Natural Scrolling Enabled" 1
	xinput set-prop "DELL0A36:00 0488:101A Touchpad" "libinput Disable While Typing Enabled" 1
	xinput set-prop "DELL0A36:00 0488:101A Touchpad" "libinput Accel Speed" 0.5
	# save a bit of power
	rfkill block bluetooth
	# more aggressive on shutting display off on the laptop
	xset +dpms             # enable display power management system
	xset dpms 300 600 1200 # standby, suspend, off; xset q to see values
	xset s blank           # blank screen on time out
	xset s 180 120         # blank tied to slock
	;;
esac

# OS specific
case "$ID" in
void)
	# void isn't a systemd distribution
	# per-user dbus setup as Void runit service
	# https://dpaste.com/7SP7MKFD6
	export DBUS_SESSION_BUS_ADDRESS="$(cat $HOME/.cache/dbus-address)"
	eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)

	export GNOME_KEYRING_CONTROL GNOME_KEYRING_PID GPG_AGENT_INFO SSH_AUTH_SOCK
	/usr/libexec/xfce-polkit & # gui polkit agent
	pipewire &                 # configured to launch wireplumber
	dunst &                    # notification daemon for X
	;;
opensuse-tumbleweed) ;;
debian) ;;
esac

xss-lock slock &                                         # set slock as the lock handler
picom -b --vsync                                         # picom provides more than eye candy
feh --no-fehbg --bg-center ~/.config/wallpaper/defaultbg # background, a symlink
tikiblocks -o xprop &                                    # status bar setting dwm's xname property
# the window manager is started by startx/.xinitrc or a display manager
