theme="nord-night"

[editor]
bufferline = "multiple" # Show currently open buffers, only when more than one exists.
cursorline = true # Highlight all lines with a cursor
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]

[keys.normal]
"tab" = ":buffer-next"
"S-tab" = ":buffer-previous"

[keys.normal.space]
"l" = ":run-shell-command $TERM -e lazygit"
