# https://github.com/LGUG2Z/helix-vim/blob/master/config.toml

theme = "nord-night"
# theme = "tokyonight_storm"

[editor]
auto-format = true
bufferline = "multiple"

color-modes = true
cursorline = true
line-number = "relative"
mouse = false
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.indent-guides]
render = true
skip-levels = 1

[editor.statusline]
left = [
  "mode",
  "spinner",
  "version-control",
  "file-name",
  "file-modification-indicator",
]

[keys.insert]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]

[keys.select]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
A-x = "extend_to_line_bounds"
X = ["extend_line_up", "extend_to_line_bounds"]

[keys.normal]
C-p = ["move_line_up", "scroll_up"]
C-n = ["move_line_down", "scroll_down"]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
"tab" = ":buffer-next"
"S-tab" = ":buffer-previous"
A-l = ":buffer-next"
A-h = ":buffer-previous"

# Alt-x shrink selection by one line
A-x = "extend_to_line_bounds"
X = ["extend_line_up", "extend_to_line_bounds"]

[keys.normal.space]
"g" = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
