# dotfiles managed by [chezmoi](https://www.chezmoi.io/) - source at https://github.com/mwyvr/dotfiles

# Obscure notes:
# shift-tab when inserting tabs in the middle of a line (due to "smart tab" feature)

# https://github.com/mwyvr/cli-themes/blob/main/helix/mui_dark.toml
theme = "mui_dark"

[editor]
bufferline = "multiple"
cursorline = true
line-number = "relative"
mouse = false
true-color = true
color-modes = true
end-of-line-diagnostics = "hint"

# persist-old-files = true # when persist branch is merged

[editor.cursor-shape]
insert = "bar"

[editor.indent-guides]
render = true
skip-levels = 1

# new in 25.01 but feels clunky
# [editor.inline-diagnostics]
# cursor-line = "error"

[editor.lsp]
display-messages = true

[editor.statusline]
left = [
  "mode",
  "spinner",
  "version-control",
  "file-name",
  "file-modification-indicator",
]

[keys.insert]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
"C-k" = ["page_cursor_half_up"]
"C-j" = ["page_cursor_half_down"]

[keys.select]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
A-x = "extend_to_line_bounds"
X = ["extend_line_up", "extend_to_line_bounds"]

[keys.normal]
C-p = ["move_line_up", "scroll_up"]
C-n = ["move_line_down", "scroll_down"]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
G = "goto_file_end"
g.q = ":reflow"
tab = ":buffer-next"
S-tab = ":buffer-previous"
A-u = ["switch_to_lowercase"]
A-S-u = ["switch_to_uppercase"]
C-k = ["page_cursor_half_up"]
C-j = ["page_cursor_half_down"]

# Alt-x shrink selection by one line
A-x = "extend_to_line_bounds"
X = ["extend_line_up", "extend_to_line_bounds"]

[keys.normal.space]
l.f = ":format"
l.g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
l.r = ":lsp-restart"
l.c = ":config-reload"
l.t = ":toggle-option auto-format"

q = ":quit"
w = ":write"
