# Add only customizations required; system defaults will work for many.
# See default configs:
# https://github.com/helix-editor/helix/blob/master/languages.toml

# https://github.com/estin/simple-completion-language-server
# Added for markdown
[language-server.scls]
command = "simple-completion-language-server"

# spelling and grammar
[language-server.harper-ls]
# https://writewithharper.com/docs/integrations/helix
command = "harper-ls"
args = ["--stdio"]

[language-server.harper-ls.config.harper-ls]
userDictPath = "~/.config/harperls-user.spell" # in code action, "global" dictionary

[language-server.harper-ls.config.harper-ls.linters]
SpellCheck = true # default

[language-server.emmet-ls]
command = "emmet-ls"
args = [ "--stdio" ]

[language-server.superhtml]
command = "superhtml"
args = [ "lsp" ]

[[language]]
name = "bash"
file-types = ["sh", "bash"]
shebangs = ["sh", "bash", "dash", "zsh"]
auto-format = true
formatter = { command = "shfmt", args = ["-i", "2", "-"] } # Example: format with 2-space indentation

[[language]]
name = "markdown" # marksman isn't directly available on musl libc Linux distribution (Chimera)
auto-format = true
formatter = { command = "prettier", args = ["--parser", "markdown"] }
file-types = ["md", "eml"]
language-servers = ["mpls", "scls", "harper-ls"]

# https://github.com/mhersson/mpls
[language-server.mpls]
command = "mpls"

# https://github.com/helix-editor/helix/blob/master/languages.toml#L898
# Customizing so including the default
[[language]]
name = "html"
scope = "text.html.basic"
injection-regex = "html"
file-types = ["html", "htm", "shtml", "xhtml", "xht", "jsp", "asp", "aspx", "jshtm", "volt", "rhtml", "cshtml"]
block-comment-tokens = { start = "<!--", end = "-->" }
language-servers = [ "vscode-html-language-server", "superhtml", "emmet-ls" ]
auto-format = true
indent = { tab-width = 2, unit = "  " }

# go templating
[[language]]
name = "templ"
language-servers = ["templ", "emmet-ls"] # add snippets
auto-format = true # off by default

[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }
language-servers = ["gopls", "golangci-lint2-langserver"]

[[language]]
name = "gotmpl"
scope = "source.gotmpl"
injection-regex = "gotmpl"
file-types = ["gotmpl", "tmpl"]
# comment-token = "<!--"
# does not work as yet:
block-comment-tokens = { start = "<!--", end = "-->" }
language-servers = ["gopls", "vscode-html-language-server", "emmet-ls"]
auto-format=true
formatter = { command = "gotmplfmt" }
indent = { tab-width = 2, unit = " " }

[language-server.golangci-lint2-langserver]
command = "golangci-lint-langserver"

# [language-server.golangci-lint2-langserver.config]
# command = [
#   "golangci-lint",
#   "run",
#   "--output.json.path",
#   "stdout",
#   "--show-stats=false",
#   "--issues-exit-code=1",
# ]


