[[languages]]
# https://github.com/helix-editor/helix/wiki/Language-Server-Configurations
# https://github.com/helix-editor/helix/wiki/External-formatter-configuration

# TODO Word completion and snippets:
# https://github.com/estin/simple-completion-language-server

# https://github.com/estin/simple-completion-language-server
[language-server.scls]
command = "simple-completion-language-server"

# https://docs.astral.sh/ruff/editors/setup/#helix
[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server]
bash-language-server = { command = "bash-language-server", args = ["start"] }

# shells
[[language]]
name = "fish"
formatter = { command = "fish_indent" }
auto-format = true

[[language]]
name = "bash"
indent = { tab-width = 4, unit = "    " }
formatter = { command = 'shfmt', args = ["-i", "4"] }
auto-format = true

# text documents
[[language]]
name = "markdown"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "markdown"] }
language-servers = ["scls", "harper-ls"]

# spelling and grammar
[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]

# configuration or data markup languages
[[language]]
name = "toml"
formatter = { command = "taplo", args = ["format", "-"] }
auto-format = true

[language-server.yaml-language-server.config.yaml]
format = { enable = true }
validation = true

[language-server.yaml-language-server.config.yaml.schemas]
"https://json.schemastore.org/github-workflow.json" = ".github/workflows/*.{yml,yaml}"
"https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-tasks.json" = "roles/{tasks,handlers}/*.{yml,yaml}"

# programming languages
[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }
language-servers = ["scls", "gopls", "golangci-lint-langserver"]

# go templating
[[language]]
name = "templ"
auto-format = true

[[language]]
name = "python"
language-servers = ["ruff"]
# In case you'd like to use ruff alongside black for code formatting:
auto-format = true
formatter = { command = "black", args = ["--quiet", "-"] }

# hypertext and related
[[language]]
name = "html"
indent.tab-width = 2
indent.unit = " "
language-servers = ["vscode-html-language-server", "emmet-ls"]
formatter = { command = 'prettier', args = [
  "--parser",
  "html",
  "--tab-width",
  "2",
] }
auto-format = true

[[language]]
name = "javascript"
indent.tab-width = 4
indent.unit = " "
language-servers = ["typescript-language-server"]
formatter = { command = 'prettier', args = [
  "--parser",
  "javascript",
  "--tab-width",
  "4",
] }
auto-format = true

[[language]]
name = "typescript"
indent.tab-width = 4
indent.unit = " "
language-servers = ["typescript-language-server"]
formatter = { command = 'prettier', args = [
  "--parser",
  "typescript",
  "--tab-width",
  "4",
] }
auto-format = true

[[language]]
name = "css"
language-servers = ["vscode-css-language-server"]
formatter = { command = 'prettier', args = ["--parser", "css"] }
auto-format = true

[[language]]
name = "json"
language-servers = ["vscode-json-language-server"]
formatter = { command = 'prettier', args = ["--parser", "json"] }
auto-format = true
