#!/bin/sh

# MAPPINGS
# These keybindings are shared across platforms

# launchers
riverctl map normal Alt+Shift Return spawn foot                                        # Alt+Shift+Return to start an instance of foot (https://codeberg.org/dnkl/foot)
riverctl map normal Super+Shift R spawn 'foot sh -c "hx ~/.config/river/*"'            # edit river config
riverctl map normal Super+Shift X spawn 'sh -c "~/.config/river/init"'                 # reload/eXecute river config
riverctl map normal Super+Shift T spawn 'foot sh -c "hx ~/.config/waybar/*"'           # edit waybar config
riverctl map normal Super+Shift L spawn 'pkill --signal USR1 swayidle'                 # (L)ock: trigger idle (and lock and suspend S0 if defined in swayidle)
riverctl map normal Super+Shift C spawn "foot ssh -t mw@wabbit tmux new -A -s chimera" # IRC
riverctl map normal Super+Shift W spawn "foot ssh -t mw@wabbit tmux new -A -s wabbit"  #
riverctl map normal Super+Shift B spawn "foot ssh -t mw@bugs tmux new -A -s bugs"      #
riverctl map normal Super+Shift E spawn "foot ssh -t mw@elron tmux new -A -s elron"    #
riverctl map normal Super+Shift P spawn "foot ssh -t mw@pi tmux new -A -s pi"          #
riverctl map normal Alt P spawn fuzzel                                                 # application menu

# kill clients, kill river
riverctl map normal Alt+Shift C close # kill focussed view (client)
riverctl map normal Alt+Shift Q exit  # terminate river

# VIEW (client/window) navigation and actions

# navigate next/previous
riverctl map normal Alt J focus-view next     # navigate to next view in layout stack
riverctl map normal Alt K focus-view previous # to previous

# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous view in the layout stack
riverctl map normal Alt+Shift J swap next
riverctl map normal Alt+Shift K swap previous

# Super+Period and Super+Comma to focus the next/previous output (display)
riverctl map normal Alt Period focus-output next
riverctl map normal Alt Comma focus-output previous

# Super+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal Alt+Shift Period send-to-output next
riverctl map normal Alt+Shift Comma send-to-output previous

# Super+Return to bump the focused view to the top of the layout stack
riverctl map normal Alt Return zoom

# Super+H and Super+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal Alt H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Alt L send-layout-cmd rivertile "main-ratio +0.05"

# Super+Shift+H and Super+Shift+L to increment/decrement the main count of rivertile(1)
# dwm: inc / dec master
riverctl map normal Alt I send-layout-cmd rivertile "main-count +1"
riverctl map normal Alt D send-layout-cmd rivertile "main-count -1"

# Super+Alt+{H,J,K,L} to move views
riverctl map normal Super+Alt H move left 100
riverctl map normal Super+Alt J move down 100
riverctl map normal Super+Alt K move up 100
riverctl map normal Super+Alt L move right 100

# Super+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal Super+Alt+Control H snap left
riverctl map normal Super+Alt+Control J snap down
riverctl map normal Super+Alt+Control K snap up
riverctl map normal Super+Alt+Control L snap right

# Super+Alt+Shift+{H,J,K,L} to resize views
riverctl map normal Super+Alt+Shift H resize horizontal -100
riverctl map normal Super+Alt+Shift J resize vertical 100
riverctl map normal Super+Alt+Shift K resize vertical -100
riverctl map normal Super+Alt+Shift L resize horizontal 100

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Super + Middle Mouse Button to toggle float
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

for i in $(seq 1 9); do
    tags=$((1 << ($i - 1)))
    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Alt $i set-focused-tags $tags
    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Alt+Shift $i set-view-tags $tags
    # Super+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags
    # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Alt 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# Super+Space to toggle float
riverctl map normal Alt Space toggle-float

# Super+F to toggle fullscreen
riverctl map normal Alt F toggle-fullscreen

# Super+{Up,Right,Down,Left} to change layout orientation
riverctl map normal Super Up send-layout-cmd rivertile "main-location top"
riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super Down send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super Left send-layout-cmd rivertile "main-location left"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode
riverctl map normal Super F11 enter-mode passthrough

# Super+F11 to return to normal mode
riverctl map passthrough Super F11 enter-mode normal
