#!/bin/sh

# this file is sourced by config/river/init
initlinux() {
    wallpaper="$HOME/.config/wallpaper/freebsd-ascii.png"
    daemons="kanshi mako waybar swaybg swayidle /usr/libexec/polkit-gnome-authentication-agent-1" # launched at end of script

    # touchpad
    # tip (see also: man riverctl):
    #  riverctl list-inputs
    #  riverctl list-input-configs
    TOUCHPAD="pointer-1160-4122-DELL0A36:00_0488:101A_Touchpad"
    riverctl input "$TOUCHPAD" tap enabled
    riverctl input "$TOUCHPAD" tap-button-map left-right-middle
    riverctl input "$TOUCHPAD" pointer-accel 0.60
    riverctl input "$TOUCHPAD" accel-profile adaptive
    riverctl input "$TOUCHPAD" disable-while-typing enabled
    riverctl input "$TOUCHPAD" scroll-method two-finger
    riverctl input "$TOUCHPAD" natural-scroll enabled

    pamixer --set-volume 60 # of 100
    brightnessctl set 15000 # ~ 16%
    # Various media key mapping examples for both normal and locked mode which do
    # not have a modifier
    for mode in normal locked; do
        # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
        riverctl map $mode None XF86AudioRaiseVolume spawn 'pamixer -i 5'
        riverctl map $mode None XF86AudioLowerVolume spawn 'pamixer -d 5'
        riverctl map $mode None XF86AudioMute spawn 'pamixer -t'
        # # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
        riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
        riverctl map $mode None XF86AudioPlay spawn 'playerctl play-pause'
        riverctl map $mode None XF86AudioPrev spawn 'playerctl previous'
        riverctl map $mode None XF86AudioNext spawn 'playerctl next'
        # # Control screen backlight brightness with brightnessctl (https://github.com/Hummer12007/brightnessctl)
        riverctl map $mode None XF86MonBrightnessUp spawn 'brightnessctl set +5%'
        riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
    done
}
