#!/bin/sh

# this file is sourced by config/river/init
initfreebsd() {
    wallpaper="$HOME/.config/wallpaper/freebsd-ascii.png"
    # daemons="kanshi mako waybar swaybg swayidle lxqt-policykit-agent" # launched at end of script
    # swaync requires xdg-desktop-portal-wlr/gtk and as a result
    # fusefs needs to be enabled/loaded
    # doas sysrc kld_list+="fusefs"
    # TODO fix XXX - dbus may be causing our sway issue/ high webkit usage on start up of evolution
    #     # Dec  1 15:43:18 elron seatd[1656]: 04:16:55.553 [INFO] [seatd/client.c:471] Client disconnected
    # Dec  1 15:43:23 elron gnome-keyring-daemon[20501]: couldn't access control socket: /var/run/xdg/mw/keyring/control: No such file or directory
    # Dec  1 15:43:23 elron gnome-keyring-daemon[20501]: discover_other_daemon: 0
    # Dec  1 15:43:23 elron gnome-keyring-daemon[20501]: couldn't connect to dbus session bus: Cannot autolaunch D-Bus without X11 $DISPLAY
    # Dec  1 15:43:23 elron syslogd: last message repeated 2 times
    # Dec  1 15:43:24 elron seatd[1656]: 04:17:00.952 [INFO] [seatd/server.c:146] New client connected (pid: 20502, uid: 1001, gid: 1001)
    # Dec  1 15:43:24 elron seatd[1656]: 04:17:00.952 [INFO] [seatd/seat.c:170] Added client 2 to seat0
    # Dec  1 15:43:24 elron seatd[1656]: 04:17:00.952 [INFO] [seatd/seat.c:480] Opened client 2 on seat0
    # Dec  1 15:43:24 elron devd[1372]: check_clients:  dropping disconnected client
    # Dec  1 15:43:24 elron syslogd: last message repeated 3 times
    # Dec  1 15:43:37 elron gnome-keyring-daemon[20705]: discover_other_daemon: 1
    # XXX FIX swaync; moved to mako for now; does not need to be started as daemon
    daemons="kanshi waybar swaybg swayidle lxqt-policykit-agent" # launched at end of script

    # touchpad
    # tip (see also: man riverctl):
    #  riverctl list-inputs
    #  riverctl list-input-configs
    # (capitalization matters)
    TOUCHPAD="pointer-1160-4122-DELL0A36:00_0488:101A_Touchpad"
    riverctl input "$TOUCHPAD" tap enabled
    riverctl input "$TOUCHPAD" tap-button-map left-right-middle
    riverctl input "$TOUCHPAD" pointer-accel 0.60
    riverctl input "$TOUCHPAD" accel-profile adaptive
    riverctl input "$TOUCHPAD" disable-while-typing enabled
    riverctl input "$TOUCHPAD" scroll-method two-finger
    riverctl input "$TOUCHPAD" natural-scroll enabled

    # Various media key mapping examples for both normal and locked mode which do not have a modifier
    mixer vol.mute=off
    for mode in normal locked; do
        # desktop feeds a DAC, don't use these there
        riverctl map $mode None XF86AudioRaiseVolume spawn 'mixer vol=+5%'
        riverctl map $mode None XF86AudioLowerVolume spawn 'mixer vol=-5%'
        riverctl map $mode None XF86AudioMute spawn 'mixer vol.mute=toggle'
    done
}
