#!/bin/sh
. /etc/os-release
OS=$(uname)

# run mappings first in case errors in script later cause it to terminate or stall
sh $HOME/.config/river/mappings

# Layout
view_padding=4
outer_padding=4
riverctl default-layout rivertile
rivertile -view-padding $view_padding -outer-padding $outer_padding &

# OSD of brightness, volume
WOBSOCK=$XDG_RUNTIME_DIR/wob.sock

case $OS in
Linux)
    daemons="kanshi swaybg swaync waybar swayidle wob"
    case $ID in
    chimera)
        swaybg_opts="-c 111318 -i $HOME/.config/wallpaper/julien-SKlFaGOrzjs-unsplash.jpg"
        ;;
    void)
        swaybg_opts="-c 111318 -i $HOME/.config/wallpaper/dino-stripe.png.jpeg"
        ;;
    *)
        swaybg_opts="-c 111318 -i $HOME/.config/wallpaper/opensuse-black.jpeg"
        ;;
    esac
    touchpad="pointer-1160-4122-DELL0A36:00_0488:101A_Touchpad"
    wpctl set-mute @DEFAULT_AUDIO_SINK@ 0

    if [ -d "/proc/acpi/button/lid" ]; then
        # laptops
        wpctl set-volume @DEFAULT_AUDIO_SINK@ 50%
        brightnessctl 13%
    else
        # desktop feeds a DAC, always leave at 100%
        wpctl set-volume @DEFAULT_AUDIO_SINK@ 100%
    fi
    # media key binds
    for mode in normal locked; do
        riverctl map $mode None XF86AudioRaiseVolume spawn "wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 5%+ \
            && wpctl get-volume @DEFAULT_AUDIO_SINK@ | cut -f 2 -d ' ' | sed -e 's/^0\.//' -e 's/\.//' > $WOBSOCK"
        riverctl map $mode None XF86AudioLowerVolume spawn "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- \
            && wpctl get-volume @DEFAULT_AUDIO_SINK@ | cut -f 2 -d ' ' | sed -e 's/^0\.//' -e 's/\.//' > $WOBSOCK"
        riverctl map $mode None XF86AudioMute spawn "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
        riverctl map $mode None XF86AudioMicMute spawn "wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"
        riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
        riverctl map $mode None XF86AudioPlay spawn 'playerctl play-pause'
        riverctl map $mode None XF86AudioPrev spawn 'playerctl previous'
        riverctl map $mode None XF86AudioNext spawn 'playerctl next'
        riverctl map $mode None XF86MonBrightnessUp spawn "brightnessctl -m s +5% | sed -r 's/.*,([0-9].*)\%+.*/\1/' > $WOBSOCK"
        riverctl map $mode None XF86MonBrightnessDown spawn "brightnessctl -m s 5%- | sed -r 's/.*,([0-9].*)\%+.*/\1/' > $WOBSOCK"
    done
    ;;
FreeBSD)
    daemons="kanshi pipewire swaybg swaync waybar swayidle"
    swaybg_opts="-c 111318 -i $HOME/.config/wallpaper/freebsd-ascii.png"
    touchpad="pointer-1160-4122-DELL0A36:00_0488:101A_TouchPad" # capitalization in TouchPad matters
    mixer vol.mute=off
    if [ "$ID" = "elron" ]; then
        # desktop feeds a DAC
        mixer vol=100%
    else
        mixer vol=60%
        for mode in normal locked; do
            riverctl map $mode None XF86AudioRaiseVolume spawn 'mixer vol=+5%'
            riverctl map $mode None XF86AudioLowerVolume spawn 'mixer vol=-5%'
            riverctl map $mode None XF86AudioMute spawn 'mixer vol.mute=toggle'
        done
    fi
    ;;
esac

# see https://wayland.freedesktop.org/libinput/doc/latest/tools.html#libinput-list-devices
riverctl input "$touchpad" tap enabled
riverctl input "$touchpad" tap-button-map left-right-middle
riverctl input "$touchpad" pointer-accel 0.40
riverctl input "$touchpad" accel-profile adaptive
riverctl input "$touchpad" disable-while-typing enabled
riverctl input "$touchpad" scroll-method two-finger
riverctl input "$touchpad" natural-scroll enabled

# GENERAL SETTINGS
riverctl focus-follows-cursor normal # none, normal, always - always is too prone to fire esp on laptop/touchpad
riverctl set-repeat 50 300           # Set keyboard repeat rate

# COLOURS
riverctl background-color 0x111318       #  surface-dim
riverctl border-color-focused 0x284777   # primary-container
riverctl border-color-unfocused 0x44474e # outline-variant
riverctl border-width 2                  # just a hint

# RULES
riverctl rule-add -title 'Compose Message' float
riverctl rule-add -app-id 'org.gnome.Evolution' -title 'Compose Message' float
riverctl rule-add -app-id 'org.gnome.Evolution' -title 'Re*' float
riverctl rule-add -app-id 'org.gnome.Evolution' -title 'Fwd*' float
riverctl rule-add -app-id 'org.gnome.Evolution-alarm-notify' float
riverctl rule-add -app-id 'org.gnome.Nautilus' float
riverctl rule-add -app-id 'org.gnome.Weather' float
riverctl rule-add -app-id 'nmtui' float # for waybar click-to-launch
riverctl rule-add -app-id 'org.pulseaudio.pavucontrol' float
riverctl rule-add -title 'Picture-in-picture' float

# gtk/gui prefs
gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'
gsettings set org.gnome.desktop.interface icon-theme 'Adwaita'
gsettings set org.gnome.desktop.interface cursor-theme 'Adwaita'
gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

# kill-daemons: only for configs while in development/tweaking
# restart="waybar swaybg wob"
restart="waybar"
# restart=""
for d in $restart; do
    case $d in
    waybar)
        # swaync-client will be relaunched by waybar's config
        pkill swaync-client
        pkill waybar
        ;;
    wob)
        pkill -f "tail.*wob"
        ;;
    *)
        pkill "$d"
        ;;
    esac
done

# start daemons not already running; note: waybar wireplumber component requires pipewire running first
for d in $daemons; do
    if ! pgrep "$d" >/dev/null 2>&1; then
        case $d in
        swaybg)
            $d $swaybg_opts &
            ;;
        wob)
            [ -e "$WOBSOCK" ] || mkfifo "$WOBSOCK"
            pkill -f "tail.*wob"
            # FreeBSD/Chimera userland's tail does not support -s interval parameter
            # tail -F -s 0 "$WOBSOCK" | wob &
            tail -F "$WOBSOCK" | wob &
            ;;
        *)
            $d &
            ;;
        esac
    fi
done
