#!/bin/sh

# run mappings first in case errors in script later cause it to terminate or stall
sh $HOME/.config/river/mappings

# set up helper daemons and OS-specific differences
. /etc/os-release
OS=$(uname)

swaybg_opts=""
view_padding=4
outer_padding=4

case $OS in
Linux)
    swaybg_opts="-c #111318 -i $HOME/.config/wallpaper/opensuse-black.jpeg"
    touchpad="pointer-1160-4122-DELL0A36:00_0488:101A_Touchpad"
    pamixer --set-volume 60 # of 100
    brightnessctl set 15000 # ~ 16%
    for mode in normal locked; do
        riverctl map $mode None XF86AudioRaiseVolume spawn 'pamixer -i 5'
        riverctl map $mode None XF86AudioLowerVolume spawn 'pamixer -d 5'
        riverctl map $mode None XF86AudioMute spawn 'pamixer -t'
        riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
        riverctl map $mode None XF86AudioPlay spawn 'playerctl play-pause'
        riverctl map $mode None XF86AudioPrev spawn 'playerctl previous'
        riverctl map $mode None XF86AudioNext spawn 'playerctl next'
        # # Control screen backlight brightness with brightnessctl (https://github.com/Hummer12007/brightnessctl)
        riverctl map $mode None XF86MonBrightnessUp spawn 'brightnessctl set +5%'
        # riverctl map $mode None XF86MonBrightnessUp spawn  "brightnessctl -q set +5% && ( echo $((`brightnessctl get` * 100 / `brightnessctl m`)) > $RIVERSOCK.wob )"
        riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
        # riverctl map $mode None XF86MonBrightnessDown spawn "brightnessctl -q set 5%- && ( echo $((`brightnessctl get` * 100 / `brightnessctl m`)) > $RIVERSOCK.wob )"
        # bindsym XF86MonBrightnessDown exec brightnessctl -q set 5%- && ( echo $((`brightnessctl get` * 100 / `brightnessctl m`)) > $SWAYSOCK.wob )
    done
    ;;
FreeBSD)
    swaybg_opts="$HOME/.config/wallpaper/freebsd-ascii.png"
    touchpad="pointer-1160-4122-DELL0A36:00_0488:101A_TouchPad" # capitalization in TouchPad matters
    mixer vol.mute=off
    for mode in normal locked; do
        # desktop feeds a DAC, don't use these there
        riverctl map $mode None XF86AudioRaiseVolume spawn 'mixer vol=+5%'
        riverctl map $mode None XF86AudioLowerVolume spawn 'mixer vol=-5%'
        riverctl map $mode None XF86AudioMute spawn 'mixer vol.mute=toggle'
    done
    ;;
esac
riverctl input "$touchpad" tap enabled
riverctl input "$touchpad" tap-button-map left-right-middle
riverctl input "$touchpad" pointer-accel 0.60
riverctl input "$touchpad" accel-profile adaptive
riverctl input "$touchpad" disable-while-typing enabled
riverctl input "$touchpad" scroll-method two-finger
riverctl input "$touchpad" natural-scroll enabled

# only needed while configs are in development
restart="rivertile waybar swaybg"
for d in $restart; do
    pkill $d
done

# start daemons not already running
daemons="rivertile swaync waybar swaybg"
for d in $daemons; do
    if ! pgrep $d 2>&1 >/dev/null; then
        case $d in
        rivertile)
            riverctl default-layout rivertile
            $d -view-padding $view_padding -outer-padding $outer_padding &
            ;;
        swaybg)
            $d $swaybg_opts &
            ;;
        *)
            $d &
            ;;
        esac
    fi
done
