inherits = "nord-night"
"ui.background" = {}
"ui.cursorline.primary" = { bg = "nord0" }
"ui.bufferline" = { fg = "nord3" }
"ui.bufferline.active" = { fg = "nord4" }
"ui.cursor.match" = { bg = "nord14", fg = "nord3" }
