import = ["~/.config/alacritty/nordfox.toml"]

[window]
dynamic_title = true
opacity = 0.95

[cursor]
style = "Block"
[font]
size = 11

[font.normal]
family = "monospace"

[font.offset]
# # vertical spacing, normalizing with foot setup
y = -2
#
