import = ["~/.config/alacritty/nordfox.toml"]

[window]
dynamic_title = true
opacity = 0.96

[font]
size = 10.3

[font.normal]
family = "IBM Plex Mono"
# family = "InconsolataGo Nerd Font Mono"

[font.offset]
y = -2

