import = ["~/.config/alacritty/nordfox.toml"]

[window]
dynamic_title = true
opacity = 0.95

[cursor]
style = "Block"
[font]
size = 10.5

[font.normal]
family = "monospace"
style = "Regular"

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.offset]
# # vertical spacing, some fonts need a bit of compression
# y = -2
#
