
[window]
dynamic_title = true
opacity = 0.95

[cursor]
style = "Block"
[font]
size = 11
# size = 11

[font.normal]
family = "monospace"

[font.offset]
# # vertical spacing, normalizing with foot setup
y = -2

[general]
# import = ["~/.config/alacritty/nordfox.toml"]
import = ["~/.config/alacritty/mui-dark.toml"]
