import = ["~/.config/alacritty/nordfox.toml"]

[colors.primary]
background = "0x2b4252"
foreground = "0xd8dee9"

[window]
dynamic_title = true
opacity = 0.95

[cursor]
style = "Block"
[font]
size = 10

[font.normal]
family = "Roboto Mono"
# family = "IBM Plex Mono"
style = "Regular"

[font.bold]
family = "Roboto Mono"
style = "Bold"

[font.bold_italic]
family = "Roboto Mono"
style = "Bold Italic"

[font.italic]
family = "Roboto Mono"
style = "Italic"

# [font.offset]
# # vertical spacing, some fonts need a bit of compression
# y = -1
#
