#!/bin/bash
# emptty text mode display manager (Void Linux: xbps-install emptty)
# https://github.com/tvrzna/emptty
# Starts the dwl window manager and supporting services
Environment=wayland

# --start connects to already running daemon or starts it
eval $(/usr/bin/gnome-keyring-daemon --start)
export SSH_AUTH_SOCK
export XKB_DEFAULT_OPTIONS=ctrl:nocaps

# audio, screen sharing and more
pipewire &
# custom content for status bar
someblocks &
#~ wallpaper - link defaultbg to your choice
wbg $HOME/.config/wallpaper/defaultbg &
# dwl window manager and status bar
dbus-launch dwl -s somebar
