#!/bin/bash
# emptty text mode display manager (Void Linux: xbps-install emptty)
# https://github.com/tvrzna/emptty
# TODO move this to a script called by a dwl.desktop file
#
# Starts the dwl window manager and supporting services
Environment=wayland

# cleanup of any stragglers
pkill pipewire

# --start connects to already running daemon or starts it
eval $(/usr/bin/gnome-keyring-daemon --start)
export SSH_AUTH_SOCK
export XKB_DEFAULT_OPTIONS=ctrl:nocaps

# content for status bar
# swaybg --image=$HOME/.config/wallpaper/defaultbg &
dbus-run-session dwl -s somebar
